language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "8"
  - "10"
before_install:
  - git submodule update --init
  - cd holiday_jp/; git fetch origin master; git reset --hard origin/master; cd ../
